<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
    /* Общие для информеров */
    'Котировки валютных пар' => 'Informan kurs valas',
    'Экономический календарь' => 'Kalender Ekonomi',    
    'Обзоры рынка' => 'Review Pasar',    
    'Виджет для яндекса' => 'Video untuk Yandex',    
    'Новостной информер' => 'Sumber berita',
    'common preamble' => '<p>Jika Anda memiliki website Anda sendiri, Anda dapat menempatkan informer mengenai Perusahaan kami. Anda akan menerima informasi terbaru dari www.masterforex.org dalam format yang nyaman untuk ditempatkan di halaman situs web Anda. Hal ini akan memungkinkan klien Anda untuk melihat bahwa situs tersebut diperbarui secara teratur. Untuk tujuan ini, berdasarkan versi yang diusulkan, pilih jenis informan dan gaya sendiri, lalu copy kode dari informan, dan tambahkanlah ke halaman situs web Anda. </p>',
    'mfri preamble' => '<h2>Informan Kutipan pasangan mata uang</h2><p>Informan kutipan pasangan mata uang akan memungkinkan Anda untuk memonitor perubahan tingkat mata uang utama secara real time. Informan menampilkan harga Bid saat ini dan harga Ask untuk tujuh pasang mata uang yang paling utama. Untuk menempatkan informan di situs Anda, cukup salin kode dan tambahkanlah ke situs web Anda. <br />
<br />
Informan MasterForex memiliki sistem pengaturan yang mudah dan fleksibel, sehingga Anda dapat menyesuaikan informan di bawah gaya dan desain situs Anda sendiri ". Pilih parameter yang diinginkan, klik Terapkan, kemudian salin kode. Untuk mengubah halaman cukup dengan refresh, maka Anda akan memiliki kesempatan untuk menyesuaikan informan lagi. Harap dicatat bahwa dalam hal kebutuhan untuk mengedit ketinggian informan yang Anda butuhkan untuk mengubah kode, mengubah blok dengan id = «mf_rates» parameter height (dalam piksel). Tinggi default informan adalah 195 piksel.  
</p>',
    'mfeci preamble' => '<h2>Informan "Kalender Ekonomi" </h2><p>Informan "Kalender Ekonomi" dari MasterForex memungkinkan pengunjung situs web Anda untuk mengikuti adanya peristiwa besar dan publikasi statistik yang mungkin memiliki dampak yang signifikan terhadap bursa keuangan dunia. Informan dapat menampilkan data dalam seminggunya dan juga memiliki kesempatan untuk memilih zona waktu yang akan membuatnya lebih nyaman bagi klien Anda. </p>',
    'mfmoi preamble' => '<h2>Informan "Laporan Bursa"</h2>
<p>Informan "Laporan Bursa" dari MasterForex memungkinkan Anda untuk melacak berita terbaru ekonomi makro, serta menerima informasi analitis terkini dari spesialis kami. Tambahkanlah ke halaman situs web Anda, maka Anda dapat selalu mengikuti perkembangan berita ekonomi penting. Untuk menempatkan informan di situs web Anda, cukup salin kode dan menambahkannya ke halaman situs web Anda. </p>',
    'mfni preamble' => '<h2>Informan "Berita"</h2>
<p>Informan "Berita" dari MasterForex akan memungkinkan Anda untuk melacak berita terbaru dan untuk menerima informasi terbaru tentang perusahaan kami. Untuk menempatkan informan di situs web Anda, cukup salin kode dan tambahkanlah ke halaman situs web Anda.</p>',
    
    /* Котировки валютных пар */
    'Цвет шапки' => 'Warna Caps ',
    'Цвет шрифта шапки' => 'Font warna',
    'Цвет фона' => 'Warna Latar Belakang',
    'Цвет шрифта' => 'Warna Font',
    'Размер шрифта' => 'Ukuran font',
    'Ширина блока' => 'Lebar blok',
    'Позиций' => 'Posisi',
    'Настройки' => 'Pengaturan',    
    'Применить' => 'Penetapan ',
    'Код информера' => 'Dapatkan kode ',

    /* Экономический календарь */
    'Временная зона' => 'Jendela sementara ',
    'Язык' => 'Bahasa',
    
    /* Обзоры рынка */
    'Ширина информера' => 'Lebar dari informan',
    'Ширина рамки' => 'Lebar bingkai',    
    'Цвет рамки' => 'Warna Bingkai',      
    'Цвет Фона' => 'Warna latar belakang ',  
    'Цвет заголовка' => 'Warna Header',  
    'Размер заголовка' => 'Ukuran header',
    'Цвет даты' => 'Warna Tanggal',    
    'Размер даты' => 'Ukuran font tanggal',        
    'Цвет заголовка новости' => 'Warna Judul Berita',
    'Размер заголовка новости' => 'Ukuran berita Header',
    'Цвет новости' => 'Warna Font Berita',    
    'Размер новости' => 'Ukuran Font Berita ',
    'Выбор языка новости' => 'Pilihan Bahasa',    
    'Количество новостей' => 'Jumlah berita',        
    'Тип баннера' => 'Jenis banner',
    'caption' => 'Judul widget',
    'description 1' => 'Dollar diperdagangkan pada level 8 bulan terendahnya terhadap euro',
    'text 1' => 'Kemarin dolar AS menyentuh level terendahnya dalam delapan bulan terhadap euro dan saat ini pada awal hari perdagangan, masih terkonsolidasi dilevel 1.383. Tekanan terbesar atas dolar masih harus menunggu kemungkinan kebijakan terbaru quantitative easing oleh the Federal Reserve AS yang secara signifikan menguat setelah the Bank of Japan mengumumkan penurunan tingkat suku bunga dan menciptakan sejumlah dana untuk membeli surat hutang pemerintahnya.',
    'description 2' => 'Harga minyak disesuaikan sebagai usaha antisipasi publiksi laporan EIA',
    'text 2' => 'Kutipan bahan mentah hari ini turun dari level tertingginya dalam lima bulan terakhir yang dicapainya selama sesi perdagangan kemarin. Alasan dari optimisme pada bursa komoditas kemarin memberikan dukungan eksternal yang positif, begitu juga dengan pelemahan tajam dolar terhadap kompetitor utama lainnya, dan statistik positif lainnya dari AS.',
	/* Информер виджет для Яндекса */
    'mfyai content' => '<h2>Widget informasi untuk Yandex</h2><p>Tambahkan widget MasterForex pada halaman utama Yandex. Ini akan memungkinkan Anda untuk mendapatkan halaman Runet yang terpopuler, lengkap dengan tinjauan ulang pasar mata uang yang presisi. </p><ul><li> Login to your account on Yandex</li><li>Entar the link <a href="http://www.yandex.ru/?edit=1&add=30388"</li>
</ul>'

    /* Новостной информер*/
);


