<?php
return array(
    "Tournaments" => "Torneos",
  "You have already registered in this round." => "Ya se ha registrado en esta ronda.",
  "You successfully registered in round." => "Se ha registrado con éxito en esta ronda.",
  "You are successfully registered in this tournament." => "Se ha registrado con éxito en este torneo.",
  "Error occured during registration." => "Ha ocurrido un error durante el registro.",
  "Nickname is not unique." => "El nombre de usuario.",
  "Conditions" => "Condiciones",
  "Participation" => "Participación",
  "Current Rounds" => "Rondas actuales",
  "Rounds History" => "Historial de las rondas",
  "Forex Drive" => "Forex Drive",
  "FX-Rodeo" => "FX-Rodeo",
  "Profit Day" => "Profit Day",
  "Your account:" => "Su cuenta:",
  "Participants" => "Participantes",
  "will be soon" => "comenzará pronto",
  "is going" => "la ronda se está celebrando",
  "is gone" => "la ronda ha finalizado",
  "You are registered" => "Está registrado",
  "You are banned" => "No puede participar en la ronda",
  "Register in this round" => "Registrarse en esta ronda",
  "In order to participate in every round of the tournament you should apply for participation in the round. Press the “Register in this round” button." => "",
  "Your nickname" => "",
  "The tournament will become available to you once you complete the phone number verification." => "",
  "To enter your personal cabinet, write in the confirm code that was sent to you by email {}." => "",
  "Current Round" => ""
);