<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
    'Contest' => 'Конкурсный',
    'CFD' => '',
  '?' => '',
  'ECN' => '',
  'Микро' => '',
  'Стандарт' => '',
  'Standard' => 'Стандарт',

  'Micro' => 'Микро',

    'infoСтандарт' => 'Вы трейдер с опытом и знаниями рынка, но привыкли к классической схеме торговли? Открывайте счет типа Standart и применяйте свои знания и опыт в привычной атмосфере.Депозит от 100 долларов.',
    'infoМикро' => 'Хотите попробовать торговать на Forex, но боитесь вкладывать много средств?Или вам нужно проверить свою торговую стратегию на прочность с минимальными вложениями? Тогда, этот тип счета для вас. Депозит всего от 1 доллара.',

    'infoMetaTrader5' => 'Любите инновации, стараетесь быть в тренде всех новинок на рынке Forex? Попробуйте торговую платформу MetaTrader5.Возможно именно она ключ к вашему успеху!
Депозит от 100 долларов',
    'infoMetaTrader5 Demo' => '',

    'infoStrict' => 'Вы привыкли реагировать даже на малейшие колебания на рынке? Ваша торговая стратегия выверена до десятой пункта? Тогда счет Strict – это то, что вам нужно. Пяти знаковые валютные пары дадут вам полный контроль над ситуацией!',
    'infoECN' => 'Вы знаете, что такое рыночное исполнение и стакан цен? Вас привлекает межбанковский рынок Forex? Откройте ECN счет, и используйте свои знания в привычной платформе MetaTrader4.',
    'infoCFD' => 'Хотите торговать CFD акций, товаров, индексов? CFD счет именно то, что вам нужно.',

);
