<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Атрибут {att} должен содержать не менее 8-ми символов' => 'Поле {att} должно содержать не менее 8-ми символов',
  'Атрибут {att} обязательно должен содержать и буквы и цифры' => 'Поле {att} обязательно должно содержать как буквы, так и цифры',
  'Атрибут {att} содержит недопустимые символы' => 'Поле {att} содержит недопустимые символы',
  'Атрибут Пароль не должен совпадать с паролями, введёнными на предыдущем шаге' => 'Значение поля Пароль не должно совпадать с паролями, введёнными на предыдущем шаге',
  'Пароль и телефонный пароль не должны совпадать' => '',
  'Атрибут {att} указан неверно.' => 'Значение поля {att} указано неверно.',
  'Вы указали номер кошелька Представительства. Представительства не участвуют в акции "Приведи друга"' => 'Вы указали номер личного кошелька Представительства. Представительства не участвуют в акции "Приведи друга"',
);
