<?php
return array(
    "Tournaments" => "竞赛",
  "You have already registered in this round." => "您已申请过此轮竞赛",
  "You successfully registered in round." => "申请竞赛成功",
  "You are successfully registered in this tournament." => "您已成功申请此次竞赛",
  "Error occured during registration." => "注册过程中发生错误",
  "Nickname is not unique." => "该昵称已被注册",
  "Conditions" => "活动相关介绍",
  "Participation" => "参与",
  "Current Rounds" => "当前竞赛",
  "Rounds History" => "竞赛历史",
  "Forex Drive" => "外汇高速路",
  "FX-Rodeo" => "FX竞技",
  "Profit Day" => "盈利日",
  "Your account:" => "您的账号：",
  "Participants" => "参加者",
  "will be soon" => "即将到来",
  "is going" => "正在进行",
  "is gone" => "已经结束",
  "You are registered" => "您已注册",
  "You are banned" => "您已被禁止",
  "Register in this round" => "注册此轮比赛",
  "In order to participate in every round of the tournament you should apply for participation in the round. Press the “Register in this round” button." => "参加每一轮比赛均需提交本轮比赛参加申请。点击“注册本轮比赛”按钮。",
  "Your nickname" => "您的昵称",
  "The tournament will become available to you once you complete the phone number verification." => "",
  "To enter your personal cabinet, write in the confirm code that was sent to you by email {}." => "",
  "Current Round" => ""
);