<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Атрибут {att} должен содержать не менее 8-ми символов' => 'Ruangan {att} hendaklah mengandungi tidak kurang dari 8 simbol',
		'Атрибут {att} обязательно должен содержать и буквы и цифры' => 'Ruangan {att} hendaklah mengandungi abjad dan nombor',
		'Атрибут {att} содержит недопустимые символы' => 'Ruangan {att} mengandungi simbol yang tidak dikenali',
		'Атрибут Пароль не должен совпадать с паролями, введёнными на предыдущем шаге' => 'Kata laluan ini tidak boleh sama dengan kata laluan yang dimasukkan pada peringkat sebelumnya',
		'Пароль и телефонный пароль не должны совпадать' => 'Kata laluan dan kata laluan telefon tidak boleh sama',
        'Атрибут {att} указан неверно.' => 'Nilai {att} adalah tidak tepat.',
        'Вы указали номер кошелька Представительства. Представительства не участвуют в акции "Приведи друга"' => 'Anda telah memasukkan maklumat nombor dompet MF yang tidak berdaftar. Wakil tidak boleh mengikuti "Refer-a-friend" action',
);
