<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
    /* Общие для информеров */
    'Котировки валютных пар' => 'Sebutharga matawang',
    'Экономический календарь' => 'Kalender ekonomi',
    'Обзоры рынка' => 'Gambaran pasaran',
    'Виджет для яндекса' => 'Wiget untuk Yandex',
    'Новостной информер' => 'Penyampai berita',
    'common preamble' => '<p>Sekiranya anda memiliki halaman sesawang,anda boleh meletakkan wiget untuk syarikat kami. Anda boleh menerima maklumat terkini dari www.masterforex.org dalam format yang sesuai didalam halaman sesawang anda. Ia membolehkan pelanggan melihat maklumat dikemaskini setiap masa. Untuk ini, berdasarkan pilihan cadangan yang sedia ada, pilih jenis pelekat dan style anda, cetak kod dan tambahkan pelekat tersebut pada halaman sesawang anda.</p>',
    'mfri preamble' => '<h2>Maklumat sebutharga pasangan matawang</h2><p>Maklumat sebutharga pasangan matawang membolehkan anda memantau perubahan kadar tukaran matawang asing utama dalam masa sebenar. Wiget yang memaparkan Bid semasa dan harga Permintaan untuk 7 (tujuh) pasangan matawang utama didalam pasaran pertukaran. Untuk menyusun pelekat pada sesawang, tiru kod dan masukkan kod tersebut kedalam muka surat.
</p>',
    'mfeci preamble' => '<h2>Maklumat "Kalender Ekonomi"</h2><p>Maklumat "Kalender Ekonomi" dari MasterForex membolehkan pelawat untuk mengikuti jadual utama dan terbitan secara statistik yang boleh memberik impak pada pasaran kewangan antarabangsa.</p>',
    'mfmoi preamble' => '<h2>Maklumat Pasaran secara keseluruhan</h2>
<p>Maklumat MasterForex «Gambaran Pasaran» membolehkan anda menikuti berita makroekonomi terkini dan menerima maklumat analitik dari pakar-pakar makroekonomi. Selepas memasukkan maklumat ini kedalam sesawang anda, anda akan mengetahui berita-berita penting mengenai ekonomi semasa dan terkini. Untuk memasukkan maklumat kedalam sesawang anda, sila salin kod dan masukkan ia kedalam sesawang anda.</p>',
    'mfni preamble' => '<h2>Maklumat "Berita"</h2>
<p>Maklumat «Berita» MasterForex membolehkan anda mengikuti berita terkini serta menerima maklumat yang tepat daripada syarikat. Untuk memasukkan maklumat kedalam sesawang anda, sila salin kod dan masukkan ia kedalam sesawang anda.</p>',
    
    /* Котировки валютных пар */
    'Цвет шапки' => 'Warna header',
    'Цвет шрифта шапки' => 'Warna font pada header',
    'Цвет фона' => 'Warna lantarbelakang',
    'Цвет шрифта' => 'Warna font',
    'Размер шрифта' => 'Saiz font',
    'Ширина блока' => 'Lebar blok',
    'Позиций' => 'Posisi',
    'Настройки' => 'Setting',
    'Применить' => 'Pohon',
    'Код информера' => 'Kod maklumat',

    /* Экономический календарь */
    'Временная зона' => 'Zon masa',
    'Язык' => 'Bahasa',
    
    /* Обзоры рынка */
    'Ширина информера' => 'Lebar maklumat',
    'Ширина рамки' => 'Lebar frame',
    'Цвет рамки' => 'Warna frame',
    'Цвет заголовка' => 'Warna tajuk',
    'Размер заголовка' => 'Sais tajuk',
    'Цвет даты' => 'Warna tarikh',
    'Размер даты' => 'Sais tarikh',
    'Цвет заголовка новости' => 'Warna tajuk berita',
    'Размер заголовка новости' => 'Sais tajuk berita',
    'Цвет новости' => 'Warna barita',
    'Размер новости' => 'Sais berita',
    'Выбор языка новости' => 'Pilihan bahasa berita',
    'Количество новостей' => 'Bilangan berita',
    'Тип баннера' => 'Jenis banner',
    'caption' => 'Tajuk wiget',
    'description 1' => 'Dollar US diniagakan pada lapan-bulan terendah berbanding dengan euro',
    'text 1' => 'Semalam, dollar U.S. mencecah paras terendah berbanding euro dalam tempoh lapan bulan dan ketika diniagakan pada dagangan, ia meneruskan jajaran untuk berada pada aras 1.383. Tekanan utama pada dollar U.S. adalah keterusan menanti petunjuk baru dari Rezab Persekutuan Amerika Syarikat selepas Bank Jepun mengumumkan penurunan pada kadar bunga dan menambah wang dana untuk membeli sekuriti hutang kerajaan.',
    'description 2' => 'Harga minyak dipasaran diunjur dalam jangkaan menanti laporan EIA yang bakal diterbitkan.',
    'text 2' => 'Sebutharga harga bahan mentah menurun dari 5 bulan teratas sewaktu didagangkan pada sesi semalam.  Sebab atas pengurangan pada pasaran harga bahan mentah memberi penunjuk luaran positif, penurunan dollar berbanding pesaing utama dan statistik positif dari USA.',
    
    /* Информер виджет для Яндекса */
    'mfyai content' => '<h2>Maklumat wiget untuk Yandex.</h2><p>Masukkan wiget kepunyaan MasterForex kedalam muka utama Yandex. Ini akan membolehkan anda, memasuki  muka utama runet  dan mendapat gambaran sebenar dan tepat pasaran matawang, </p><ul><li>Masukkan kata laluan didalam Yandec</li><li>klik pada sambungan<a href="http://www.yandex.ru/?edit=1&add=30388" target="_blank">http://www.yandex.ru/?edit=1&add=30388 </a></li><li>klik "Keluar" dan perbetulkan lokasi blok pada muka utama</li><li>Pada sudut atas disebelah kanan klik "Simpan"</li>
</ul>'

    /* Новостной информер*/
    
);
