<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'ECN' => '',
    'Ваш счёт №{tradingAccountId} успешно перенесён.' => 'Your account was successfully transferred',
    'Доллар' => 'Dollar',
    'Не удалось перенести торговый счет.' => 'Your account was not transferred',
    'Номер счёта' => 'Nombor akaun',
    'Отправить заявку' => 'Hantar permintaan',
    'Перенос торгового счёта' => 'Isian semula akaun dagangan',
    'Тип счёта' => 'Jenis Akaun',
    'Цент' => 'Cent',
    'Пароль к торговому счёту' => 'Traders password',
    'Пинкод' => 'Pincode',
    'Назад' => 'Kembali',
);
