<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
    'Get a new code' => 'Dapatkan kod baru',
    '{attribute} cannot be blank.' => 'Petak {attribute} seharusnya tidak dibiarkan kosong.',
    'The verification code is incorrect.' => 'Kod salah. Masukkan kod baru.',
    'The file "{file}" cannot be uploaded. Only files with these extensions are allowed: {extensions}.' => 'Fail "{file}" tidak dapat dimuat-naik. Hanya fail yang mengandungi akhiran berikut dibenarkan : {extensions}.',
    'The file "{file}" is too large. Its size cannot exceed {limit} bytes.' => 'Fail "{file}" adalah terlalu besar. Saiz fail hendaklah tidak melebihi {limit} byte.',
);
