<?php
return array(
    "Tournaments" => "Tournaments",
  "You have already registered in this round." => "You have already registered in this round.",
  "You successfully registered in round." => "You successfully registered in round.",
  "You are successfully registered in this tournament." => "You are successfully registered in this tournament.",
  "Error occured during registration." => "Error occured during registration.",
  "Nickname is not unique." => "Nickname is not unique.",
  "Conditions" => "Conditions",
  "Participation" => "Participation",
  "Current Rounds" => "Current Rounds",
  "Rounds History" => "Rounds History",
  "Forex Drive" => "Forex Drive",
  "FX-Rodeo" => "FX-Rodeo",
  "Profit Day" => "Profit Day",
  "Your account:" => "Your account:",
  "Participants" => "Participants",
  "will be soon" => "starting soon",
  "is going" => "currently in progress",
  "is gone" => "finished",
  "You are registered" => "You are registered",
  "You are banned" => "You are banned",
  "Register in this round" => "Register in this round",
  "In order to participate in every round of the tournament you should apply for participation in the round. Press the “Register in this round” button." => "In order to participate in every round of the tournament you should apply for participation in the round. Press the “Register in this round” button.",
  "Your nickname" => "Your nickname",
  "The tournament will become available to you once you complete the phone number verification." => "The tournament will become available to you once you complete the phone number verification.",
  "To enter your personal cabinet, write in the confirm code that was sent to you by email {}." => "To enter your personal cabinet, write in the confirm code that was sent to you by email {}.",
  "Current Round" => "Current Round"
);