<?php
return array(
    "Tournaments" => "الدورات",
  "You have already registered in this round." => " لقد  قمت بالفعل بالتسجيل في هذه الجولة. ",
  "You successfully registered in round." => " لقد قمت بالتسجيل بنجاح في الجولة.",
  "You are successfully registered in this tournament." => "لقد قمت بالتسجيل بنجاح في هذه الدورة",
  "Error occured during registration." => "حدث خطأ أثناء التسجيل.",
  "Nickname is not unique." => "الإسم المستعار ليس فريد.",
  "Conditions" => "الشروط ",
  "Participation" => "المشاركة",
  "Current Rounds" => "الجولات الحالية",
  "Rounds History" => "سجل الجولات",
  "Forex Drive" => "Forex Drive",
  "FX-Rodeo" => "FX-Rodeo",
  "Profit Day" => "يوم الربح",
  "Your account:" => "حسابك الخاص :",
  "Participants" => "المشاركون",
  "will be soon" => "البداية قريباً",
  "is going" => "يتم حالياً",
  "is gone" => "الأنتهاء",
  "You are registered" => "لقد تم تسجيلك",
  "You are banned" => "لقد تم حظرك",
  "Register in this round" => "التسجيل في الجولة",
  "In order to participate in every round of the tournament you should apply for participation in the round. Press the “Register in this round” button." => "",
  "Your nickname" => "",
  "The tournament will become available to you once you complete the phone number verification." => "",
  "To enter your personal cabinet, write in the confirm code that was sent to you by email {}." => "",
  "Current Round" => ""
);